module.exports = {
 API_KEY: 'KEY HERE',
 API_SECRET: 'KEY HERE',
 ACCESS_TOKEN: 'KEY HERE',
 ACCESS_TOKEN_SECRET: 'KEY HERE',
 GOOGLE_MAP_API: 'KEY HERE',
 WALKSCORE_API: 'KEY HERE',
 INDICO_API: 'KEY HERE'
}
